with text_messages; use text_messages;

package narration is

   TM_narration_intro1 : Text_Message_type := Construct_Message("Chthonaia, translated means the Undergaia. Sometimes it is referred to as the Land. It is home to vermin, aberrations, undead, demons and trogs, and now humans. Trogs are a sentient species native to Chthonaia. They are human-like but shorter in general, and have pale faintly luminescent skin. When hunting, they cover themselves in mud to mask their intrinsic illumination. The trogs are organized into tribes with a very lateral power structure, though there is usually a decided elder who sometimes possesses some magical abilities. Trogs speak Chthonaic, an ancient and forgotten language, trogs have no writings.");
   TM_narration_intro2 : Text_Message_type := Construct_Message("The demons of Chthonaia are sentient also, but they've lost it to rage and lust. They are the most feared denizens of the Undergaia and they live in the lowest parts of the caves called the Edge of the Abyss. Their skin is like stone, and they speak in Chthonaic, summoning dark servants to their side. They stand at 10 feet tall, just barely able to fit through most passages in the Land. They have a civilization of a kind, but it is rent with in-fighting and backstabbing. Neshutan, Lord Leviathan of the Lowerarchy, is the most despised of the demons and the most powerful. He coils through mazes of tunnels in the Edge of the Abyss and his scales are made of steel. Neshutan's dragonspawn are called the Immade Neshutani (or ethereal seraphim) and they find sentient hosts to secretly burrow in and exert vile influence. The Neshutani are invisible except to certain ones of keen spiritual vision. Many humans are infected by the ethereal seraphim, including those of high power in the Upper Order and Lower Alliance, but it is less endemic among trogs. Perhaps that's why their inter-community conflict is less intense.");
   TM_narration_intro3 : Text_Message_type := Construct_Message("Vermin, aberrations and undead are typical monsters of dark and dangerous places. Vermin usually keep to their own business unless cornered, but aberrations and undead will seek out adventurers to kill them quite purposefully. Aberrations are creatures that demons have infested with their insanity. No one knows why the dead rise to unlife as undead.");
   TM_narration_intro4 : Text_Message_type := Construct_Message("The humans are the newest inhabitants to Chthonaia. They lived in Gaia until Neshutan deceived them into ignoring the word of their High King and entered His dungeon in search of powerful treasure. Upon setting foot in the dungeon, the Chthonaic Curse imprisoned them and they have been here many thousands of years since. They've adapted reasonably well, though two factions lately have ruled the lives of most humans. There's the Upper Order, consisting of 3 municipalities, the Lower Alliance consisting of 2 municipalities. There's also 1 neutral municipality. As of right now, there is not war between the two factions, though it is precipitously close. There are peace talks in Seek.");

end narration;
